apiVersion: v1
kind: Service
metadata:
  name: microservicio-productos
spec:
  selector:
    app: microservicio-productos
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
  type: ClusterIP